name: CI

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.23.2

      - name: Verify dependencies
        run: go mod verify && go mod tidy

      - name: Build
        run: go build -v ./cmd/auth-service

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.23.2

      - name: Install dependencies
        run: go mod download && go mod tidy

      - name: Run tests
        run: go test ./... -v --cover
